	branch-defaults:
  master:
    environment: Web server environment
    group_suffix: null

global:
  application_name: springboot
  default_region: us-east-1
  default_platform: java11
  default_platform_version: corretto11
  sc: git

